# Generated by Django 3.1.3 on 2020-11-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('puplished_at', models.DateTimeField(auto_now_add=True)),
                ('the_book', models.FileField(upload_to='book/')),
                ('about_book', models.CharField(max_length=200)),
            ],
        ),
    ]
