# Generated by Django 3.1.3 on 2020-11-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about_book',
            field=models.TextField(max_length=200),
        ),
    ]
